# Generated by Django 2.1.7 on 2019-04-17 06:07

import Admin.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffId', models.CharField(max_length=20)),
                ('StaffName', models.CharField(max_length=30)),
                ('ContactNumber', models.BigIntegerField()),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('StaffImage', models.ImageField(upload_to='StaffImages')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabs', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.BigIntegerField()),
                ('InvoiceDate', models.DateField()),
                ('StockEntryDate', models.DateField()),
                ('RecievedFrom', models.CharField(max_length=40)),
                ('TotalCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OPDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OPNumber', models.CharField(blank=True, default=Admin.models.increment_op_number, max_length=500, null=True)),
                ('AdmissionNumber', models.BigIntegerField()),
                ('IssueDate', models.DateField(default=datetime.date.today)),
                ('TotalBalance', models.IntegerField(default=0)),
                ('Status', models.CharField(default='False', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyAvailableStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabs', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyIssuedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockEntryDate', models.DateField()),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabsIssued', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
                ('TotalCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMedicineIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabsIssued', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
                ('Op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.OPDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmissionNumber', models.BigIntegerField()),
                ('OPNumber', models.IntegerField()),
                ('IssueDate', models.DateField()),
                ('TotalBalance', models.IntegerField()),
                ('StudentName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabsRecieved', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
                ('Invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Invoice')),
            ],
        ),
    ]
