# Generated by Django 2.1.7 on 2019-03-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffId', models.CharField(max_length=20)),
                ('StaffName', models.CharField(max_length=30)),
                ('ContactNumber', models.BigIntegerField()),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('StaffImage', models.ImageField(upload_to='StaffImages')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabs', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.BigIntegerField()),
                ('InvoiceDate', models.DateField()),
                ('StockEntryDate', models.DateField()),
                ('RecievedFrom', models.CharField(max_length=40)),
                ('TotalCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyAvailableStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabs', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyIssuedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockEntryDate', models.DateField()),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabsIssued', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
                ('TotalCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMedicineIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabsIssued', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentTabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmissionNnumber', models.BigIntegerField()),
                ('OPNumber', models.IntegerField()),
                ('IssueDate', models.DateField()),
                ('TotalBalance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TabDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TabletName', models.CharField(max_length=20)),
                ('TotalTabsRecieved', models.IntegerField()),
                ('RatePerUnit', models.IntegerField()),
                ('Invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='studentmedicineissue',
            name='Op_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.StudentTabDetails'),
        ),
    ]
