# Generated by Django 2.1.7 on 2019-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstaff',
            name='StaffImage',
            field=models.ImageField(upload_to='StaffImages/'),
        ),
    ]
